<template>
  <div class="content-page">
    <PageHeader title="会话" description="按 QQ 群或单聊配置触发规则、上下文和知识库。"><el-button :icon="Refresh" @click="load">刷新</el-button></PageHeader>
    <div class="toolbar"><el-input v-model="search" placeholder="搜索群名称或会话 ID" :prefix-icon="Search" clearable /><el-select v-model="type"><el-option label="全部会话" value="all" /><el-option label="群聊" value="group" /><el-option label="单聊" value="c2c" /></el-select><el-select v-model="trigger"><el-option label="全部触发模式" value="all" /><el-option label="仅 @ 触发" value="mention_only" /><el-option label="始终触发" value="always" /><el-option label="已禁用" value="disabled" /></el-select></div>
    <section class="table-panel"><el-table :data="filtered" row-key="id"><el-table-column label="会话" min-width="240"><template #default="{ row }"><div class="cell-primary"><span class="entity-icon small"><el-icon><ChatDotRound /></el-icon></span><span><strong>{{ row.name }}</strong><small>{{ row.botName }} · {{ row.type === 'group' ? 'QQ群聊' : 'QQ单聊' }}</small></span></div></template></el-table-column><el-table-column prop="type" label="类型" width="90"><template #default="{ row }">{{ row.type === 'group' ? '群聊' : '单聊' }}</template></el-table-column><el-table-column label="触发模式" width="170"><template #default="{ row }"><div class="trigger-status"><el-tag effect="plain">{{ triggerText(row.triggerMode) }}</el-tag><small v-if="row.type === 'group' && row.triggerMode === 'always' && !row.hasFullMessageEvents">未收到全量事件</small></div></template></el-table-column><el-table-column prop="memberCount" label="已识别成员" width="110" /><el-table-column prop="messageCount" label="消息数" width="110" /><el-table-column label="知识库" min-width="190"><template #default="{ row }"><span class="muted">{{ row.knowledgeBaseNames.join('、') || '未绑定' }}</span></template></el-table-column><el-table-column prop="lastActiveAt" label="最近活跃" width="170" /><el-table-column label="状态" width="100"><template #default="{ row }"><StatusBadge :status="row.enabled ? 'success' : 'offline'" :text="row.enabled ? '启用' : '停用'" /></template></el-table-column><el-table-column label="操作" width="90" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="edit(row)">配置</el-button></template></el-table-column></el-table></section>
    <el-drawer v-model="drawer" title="会话配置" size="480px"><el-form label-position="top"><el-form-item label="会话名称"><el-input v-model="editing.name" /><small class="form-tip">QQ 群聊和单聊事件不提供群名称或昵称，可在这里设置便于识别的名称。</small></el-form-item><el-form-item label="触发模式"><el-radio-group v-model="editing.triggerMode"><el-radio-button value="mention_only">仅 @ 机器人</el-radio-button><el-radio-button value="always">始终回复</el-radio-button><el-radio-button value="disabled">禁用</el-radio-button></el-radio-group></el-form-item><el-alert v-if="editing.type === 'group' && editing.triggerMode === 'always' && !editing.hasFullMessageEvents" title="尚未收到群全量消息事件" description="始终回复依赖 GROUP_MESSAGE_CREATE。请确认开放平台已订阅群聊全量消息，并由群主允许机器人接收群内全部消息。" type="warning" :closable="false" show-icon /><el-form-item label="对话模型"><el-select v-model="editing.chatProfileId" clearable><el-option v-for="model in chatModels" :key="model.id" :label="`${model.name} · ${model.model}`" :value="model.id" /></el-select></el-form-item><el-form-item label="上下文消息数"><el-slider v-model="editing.contextLimit" :min="4" :max="50" show-input /></el-form-item><el-form-item label="系统提示词"><el-input v-model="editing.systemPrompt" type="textarea" :rows="5" placeholder="定义机器人在该会话中的角色和回答边界" /></el-form-item><el-form-item label="绑定知识库"><el-select v-model="editing.knowledgeBaseIds" multiple><el-option v-for="kb in knowledgeBases" :key="kb.id" :label="kb.name" :value="kb.id" /></el-select></el-form-item></el-form><template #footer><el-button @click="drawer = false">取消</el-button><el-button type="primary" @click="save">保存设置</el-button></template></el-drawer>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'; import { ChatDotRound, Refresh, Search } from '@element-plus/icons-vue'; import { ElMessage } from 'element-plus'; import { api } from '@/api'; import PageHeader from '@/components/PageHeader.vue'; import StatusBadge from '@/components/StatusBadge.vue'; import type { Conversation, KnowledgeBase, ModelProfile } from '@/types'
const conversations = ref<Conversation[]>([]); const knowledgeBases=ref<KnowledgeBase[]>([]); const models=ref<ModelProfile[]>([]); const search = ref(''); const type = ref('all'); const trigger = ref('all'); const drawer = ref(false); const editing = reactive<Conversation>({} as Conversation); const chatModels=computed(()=>models.value.filter(model=>model.kind==='chat'))
const filtered = computed(() => conversations.value.filter(c => (!search.value || `${c.name}${c.id}`.includes(search.value)) && (type.value === 'all' || c.type === type.value) && (trigger.value === 'all' || c.triggerMode === trigger.value)))
onMounted(load); async function load() { const [items,kbs,modelItems]=await Promise.all([api.conversations.list(),api.knowledge.list(),api.models.list()]);knowledgeBases.value=kbs;models.value=modelItems;await Promise.all(items.map(async item=>{try{const detail=await api.conversations.detail(item.id);item.knowledgeBaseIds=detail.knowledgeBaseIds||[];item.knowledgeBaseNames=item.knowledgeBaseIds.map(id=>kbs.find(kb=>kb.id===id)?.name||id);item.chatProfileId=detail.chatProfileId||'';item.systemPrompt=detail.systemPrompt||item.systemPrompt}catch{/* mock data already contains detail */}}));conversations.value=items }
function triggerText(value: string) { return ({ mention_only: '仅 @ 触发', always: '始终触发', disabled: '已禁用' } as Record<string,string>)[value] }
function edit(row: Conversation) { Object.assign(editing, row, { knowledgeBaseNames: [...row.knowledgeBaseNames], knowledgeBaseIds: [...row.knowledgeBaseIds] }); drawer.value = true }
async function save() { editing.enabled=editing.triggerMode!=='disabled';await api.conversations.save(editing.id, editing); await load(); drawer.value = false; ElMessage.success('会话配置已保存') }
</script>
