<template>
  <div class="content-page">
    <PageHeader title="知识库" description="管理 TXT、Markdown 文档，跟踪分块和向量索引进度。"><el-button :icon="Search" @click="testVisible = true">检索测试</el-button><el-button type="primary" :icon="Plus" @click="createVisible = true">新建知识库</el-button></PageHeader>
    <div class="knowledge-layout"><aside class="knowledge-list-panel"><el-input v-model="search" placeholder="搜索知识库" :prefix-icon="Search" clearable /><button v-for="kb in filtered" :key="kb.id" class="knowledge-list-item" :class="{ active: selected?.id === kb.id }" @click="selectKb(kb)"><span class="entity-icon small"><el-icon><Collection /></el-icon></span><span><strong>{{ kb.name }}</strong><small>{{ kb.documents }} 篇文档 · {{ kb.chunks }} 分块</small></span><StatusBadge :status="kb.status" :text="kb.progress === 100 ? '完成' : `${kb.progress}%`" /></button></aside>
      <section v-if="selected" class="knowledge-detail panel-surface"><div class="knowledge-detail-head"><div><span class="scope-tag">{{ scopeText(selected.scope) }}</span><h2>{{ selected.name }}</h2><p>{{ selected.description }}</p></div><div><el-button :icon="Refresh" @click="retry">重新索引</el-button><el-upload :show-file-list="false" :before-upload="upload"><el-button type="primary" :icon="Upload">上传文档</el-button></el-upload></div></div><div class="knowledge-summary"><div><span>文档</span><strong>{{ selected.documents }}</strong></div><div><span>分块</span><strong>{{ selected.chunks.toLocaleString() }}</strong></div><div><span>Embedding</span><strong>{{ selected.model }}</strong></div><div><span>索引进度</span><strong>{{ selected.progress }}%</strong></div></div><el-progress :percentage="selected.progress" :stroke-width="8" />
      <div class="section-title"><h3>文档</h3><span>支持 .txt、.md，单文件不超过 10 MB</span></div><el-table :data="selected.documentList"><el-table-column label="文件名" min-width="240"><template #default="{ row }"><div class="cell-primary"><span class="file-type">{{ row.type }}</span><span><strong>{{ row.name }}</strong><small>{{ row.size }}</small></span></div></template></el-table-column><el-table-column prop="chunks" label="分块" width="80" /><el-table-column label="状态" width="100"><template #default="{ row }"><StatusBadge :status="row.status" /></template></el-table-column><el-table-column label="失败原因" min-width="220"><template #default="{ row }"><div v-if="row.lastError" class="document-error"><span>{{ row.lastError }}</span><el-button link type="primary" @click="showError(row.name,row.lastError)">完整原因</el-button></div><span v-else class="muted">—</span></template></el-table-column><el-table-column prop="updatedAt" label="更新时间" width="140" /><el-table-column label="操作" width="100"><template #default="{ row }"><el-button v-if="row.status === 'failed' || row.lastError" link type="primary" @click="retryDocument(row.id)">重试</el-button><span v-else class="muted">—</span></template></el-table-column><template #empty><el-empty description="暂无文档，上传 TXT 或 Markdown 开始构建知识库" /></template></el-table></section></div>
    <el-dialog v-model="createVisible" title="新建知识库" width="520px"><el-form label-position="top"><el-form-item label="知识库名称"><el-input v-model="createForm.name" /></el-form-item><el-form-item label="说明"><el-input v-model="createForm.description" type="textarea" :rows="3" /></el-form-item><el-form-item label="Embedding 模型"><el-select v-model="createForm.embeddingProfileId"><el-option v-for="model in embeddingModels" :key="model.id" :label="`${model.name} · ${model.model}`" :value="model.id" /></el-select></el-form-item></el-form><template #footer><el-button @click="createVisible=false">取消</el-button><el-button type="primary" @click="createKb">创建</el-button></template></el-dialog>
    <el-dialog v-model="testVisible" title="知识检索测试" width="660px"><el-form label-position="top"><el-form-item label="选择知识库"><el-select v-model="testKb"><el-option v-for="kb in bases" :key="kb.id" :label="kb.name" :value="kb.id" /></el-select></el-form-item><el-form-item label="测试问题"><el-input v-model="testQuery" type="textarea" :rows="3" placeholder="输入一个真实用户问题" /></el-form-item><el-button type="primary" :loading="testing" @click="runTest">开始检索</el-button></el-form><div v-if="testResults.length" class="test-results"><div v-for="result in testResults" :key="result.content"><strong>相似度 {{ (result.score*100).toFixed(1) }}%</strong><p>{{ result.content }}</p></div></div></el-dialog>
    <el-dialog v-model="errorVisible" :title="errorTitle" width="620px"><pre class="error-detail-text">{{ selectedError }}</pre><template #footer><el-button :icon="CopyDocument" @click="copyError">复制原因</el-button><el-button type="primary" @click="errorVisible=false">关闭</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'; import { Collection, CopyDocument, Plus, Refresh, Search, Upload } from '@element-plus/icons-vue'; import { ElMessage } from 'element-plus'; import { api, sanitizeServiceError } from '@/api'; import PageHeader from '@/components/PageHeader.vue'; import StatusBadge from '@/components/StatusBadge.vue'; import type { KnowledgeBase, ModelProfile } from '@/types'
const bases=ref<KnowledgeBase[]>([]), models=ref<ModelProfile[]>([]), selected=ref<KnowledgeBase>(), search=ref(''), createVisible=ref(false), testVisible=ref(false), errorVisible=ref(false), errorTitle=ref('失败原因'), selectedError=ref(''), testKb=ref(''), testQuery=ref('机器人如何接收 QQ 消息？'), testing=ref(false), testResults=ref<Array<{content:string;score:number}>>([]); const createForm=reactive({name:'',description:'',embeddingProfileId:''}); const filtered=computed(()=>bases.value.filter(k=>!search.value||`${k.name}${k.description}`.includes(search.value)));const embeddingModels=computed(()=>models.value.filter(model=>model.kind==='embedding'))
onMounted(load);async function load(){[bases.value,models.value]=await Promise.all([api.knowledge.list(),api.models.list()]);if(!createForm.embeddingProfileId)createForm.embeddingProfileId=embeddingModels.value[0]?.id||'';if(!selected.value&&bases.value[0])await selectKb(bases.value[0]);testKb.value=testKb.value||bases.value[0]?.id||''};async function selectKb(kb:KnowledgeBase){try{selected.value=await api.knowledge.get(kb.id)}catch{selected.value=kb}}function scopeText(v:string){return ({global:'全局',bot:'机器人级',conversation:'会话级'} as Record<string,string>)[v]};function showError(name:string,error:string){errorTitle.value=`${name} · 失败原因`;selectedError.value=error;errorVisible.value=true}async function copyError(){await navigator.clipboard?.writeText(selectedError.value);ElMessage.success('失败原因已复制')}async function retry(){if(!selected.value)return;const failed=selected.value.documentList.filter(document=>document.status==='failed');if(!failed.length){ElMessage.info('当前没有失败文档');return}await Promise.all(failed.map(document=>api.knowledge.retryDocument(selected.value!.id,document.id)));await selectKb(selected.value);ElMessage.success('失败文档已重新加入索引队列')};async function retryDocument(documentId:string){if(!selected.value)return;await api.knowledge.retryDocument(selected.value.id,documentId);await selectKb(selected.value);ElMessage.success('文档已重新加入索引队列')};async function upload(file:File){if(!selected.value)return false;if(!/\.(txt|md)$/i.test(file.name)){ElMessage.error('仅支持 TXT 和 Markdown 文件');return false}if(file.size>10*1024*1024){ElMessage.error('单文件不能超过 10 MB');return false}try{await api.knowledge.upload(selected.value.id,file);await selectKb(selected.value);ElMessage.success('文档已上传，正在索引')}catch(error){ElMessage.error(sanitizeServiceError(error instanceof Error?error.message:'文档上传失败')||'文档上传失败')}return false};async function createKb(){if(!createForm.name.trim()||!createForm.embeddingProfileId){ElMessage.error('请填写名称并选择 Embedding 模型');return}const result=await api.knowledge.create(createForm.name,createForm.description,createForm.embeddingProfileId);createVisible.value=false;await load();const created=bases.value.find(base=>base.id===result.id)||bases.value[0];if(created)await selectKb(created);Object.assign(createForm,{name:'',description:'',embeddingProfileId:embeddingModels.value[0]?.id||''});ElMessage.success('知识库已创建')};async function runTest(){if(!testKb.value||!testQuery.value)return;testing.value=true;try{testResults.value=await api.knowledge.test(testKb.value,testQuery.value)}finally{testing.value=false}}
</script>
