<template>
  <div class="content-page">
    <PageHeader title="消息记录" description="查看从 QQ 事件、知识检索、模型生成到消息投递的完整链路。"><el-button :icon="Download" @click="exportRows">导出记录</el-button><el-button :icon="Refresh" @click="load">刷新</el-button></PageHeader>
    <div class="toolbar"><el-input v-model="search" placeholder="搜索问题、回复、发送者或 Trace ID" :prefix-icon="Search" clearable /><el-select v-model="status"><el-option label="全部状态" value="all" /><el-option label="处理成功" value="success" /><el-option label="处理失败" value="failed" /></el-select><el-date-picker v-model="date" type="date" placeholder="选择日期" /></div>
    <section class="table-panel"><el-table :data="filtered"><el-table-column prop="time" label="时间" width="170" /><el-table-column label="消息" min-width="340"><template #default="{ row }"><div class="message-preview"><strong>{{ row.question }}</strong><span>{{ row.answer || '未生成回复' }}</span></div></template></el-table-column><el-table-column label="机器人 / 会话" min-width="180"><template #default="{ row }"><div class="stacked-cell"><strong>{{ row.botName }}</strong><span>{{ row.conversationName }}</span></div></template></el-table-column><el-table-column prop="sender" label="发送者" width="100" /><el-table-column label="模型" width="130"><template #default="{ row }"><span>{{ row.model }}</span><small class="table-sub">{{ row.tokens }} tokens</small></template></el-table-column><el-table-column label="知识命中" width="100"><template #default="{ row }">{{ row.knowledgeHits }} 条</template></el-table-column><el-table-column label="耗时" width="100"><template #default="{ row }">{{ formatDuration(row.latency) }}</template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><StatusBadge :status="row.status" /></template></el-table-column><el-table-column label="操作" width="90" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="open(row)">详情</el-button></template></el-table-column></el-table></section>
    <el-drawer v-model="drawer" title="消息处理详情" size="620px"><template v-if="selected"><div class="trace-summary"><StatusBadge :status="selected.status" /><strong>{{ selected.traceId }}</strong><span>{{ selected.time }}</span></div><div class="detail-section"><h3>用户消息</h3><div class="content-box">{{ selected.question }}</div></div><div class="trace-flow"><div v-for="(step,index) in traceSteps" :key="step.title" class="trace-step" :class="step.status"><span>{{ index + 1 }}</span><div><strong>{{ step.title }}</strong><p>{{ step.description }}</p></div><em>{{ step.duration }}</em></div></div><div class="detail-section"><h3>机器人回复</h3><div class="content-box">{{ selected.answer || '处理失败，未生成回复。' }}</div></div><div class="detail-section"><h3>请求信息</h3><dl class="detail-list"><div><dt>事件类型</dt><dd>{{ selected.eventType }}</dd></div><div><dt>模型</dt><dd>{{ selected.model }}</dd></div><div><dt>知识命中</dt><dd>{{ selected.knowledgeHits }} 条</dd></div><div><dt>投递状态</dt><dd><StatusBadge :status="selected.deliveryStatus" /></dd></div></dl></div></template></el-drawer>
  </div>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { Download, Refresh, Search } from '@element-plus/icons-vue'; import { ElMessage } from 'element-plus'; import { api } from '@/api'; import PageHeader from '@/components/PageHeader.vue'; import StatusBadge from '@/components/StatusBadge.vue'; import type { MessageRecord } from '@/types'; import { formatDuration } from '@/utils/format'
const messages = ref<MessageRecord[]>([]); const search = ref(''); const status = ref('all'); const date = ref(''); const drawer = ref(false); const selected = ref<MessageRecord>();
const filtered = computed(() => messages.value.filter(m => (!search.value || `${m.question}${m.answer}${m.sender}${m.traceId}`.includes(search.value)) && (status.value === 'all' || m.status === status.value)))
const traceSteps = computed(() => selected.value ? [{ title: 'QQ 事件接收', description: selected.value.eventType, duration: '120ms', status: 'success' }, { title: '上下文构建', description: '加载最近 20 条有效消息', duration: '210ms', status: 'success' }, { title: '知识检索', description: `召回 ${selected.value.knowledgeHits} 条知识片段`, duration: selected.value.status === 'failed' ? '5.20s' : '320ms', status: selected.value.status }, { title: '模型生成', description: selected.value.model, duration: selected.value.status === 'failed' ? '—' : '820ms', status: selected.value.status }, { title: 'QQ 消息投递', description: selected.value.deliveryStatus === 'success' ? '发送成功' : '未投递', duration: selected.value.deliveryStatus === 'success' ? '280ms' : '—', status: selected.value.deliveryStatus }] : [])
onMounted(load); async function load() { messages.value = await api.messages.list() }; function open(row: MessageRecord) { selected.value = row; drawer.value = true }; function exportRows() { const csv = ['时间,机器人,会话,问题,状态', ...filtered.value.map(m => `"${m.time}","${m.botName}","${m.conversationName}","${m.question.replaceAll('"','""')}","${m.status}"`)].join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'})); a.download='messages.csv'; a.click(); URL.revokeObjectURL(a.href); ElMessage.success('消息记录已导出') }
</script>
