<template>
  <div class="content-page">
    <PageHeader title="模型" description="统一配置 OpenAI 兼容的对话和 Embedding 服务。"><el-button type="primary" :icon="Plus" @click="openCreate">添加模型配置</el-button></PageHeader>
    <el-tabs v-model="activeKind"><el-tab-pane label="对话模型" name="chat" /><el-tab-pane label="Embedding 模型" name="embedding" /></el-tabs>
    <div class="model-grid"><article v-for="model in filtered" :key="model.id" class="entity-card model-card"><div class="entity-card-head"><span class="entity-icon purple"><el-icon><MagicStick /></el-icon></span><div><h3>{{ model.name }}</h3><p>{{ model.provider }}</p></div><StatusBadge :status="model.status" /></div><dl><div><dt>模型名称</dt><dd>{{ model.model }}</dd></div><div><dt>Base URL</dt><dd class="truncate">{{ model.baseUrl }}</dd></div><div><dt>API Key</dt><dd>{{ model.maskedKey }}</dd></div><div v-if="model.kind === 'chat'"><dt>联网搜索</dt><dd>{{ searchModeText(model.webSearchMode) }}</dd></div><div v-if="model.kind === 'chat'"><dt>思考等级</dt><dd>{{ reasoningText(model.reasoningEffort) }}</dd></div><div v-if="model.kind === 'embedding' && model.dimension"><dt>向量维度</dt><dd>{{ model.dimension }}</dd></div><div><dt>最近延迟</dt><dd>{{ model.latency ? `${model.latency}ms` : '—' }}</dd></div></dl><div class="entity-card-foot"><el-button @click="openWorkbench(model)">{{ model.kind === 'chat' ? '对话测试' : '向量测试' }}</el-button><span class="spacer" /><el-button type="primary" plain @click="edit(model)">配置</el-button></div></article></div>

    <el-dialog v-model="dialog" :title="form.id?'配置模型':'添加模型配置'" width="620px"><el-form label-position="top"><div class="form-grid"><el-form-item label="配置名称"><el-input v-model="form.name" /></el-form-item><el-form-item label="模型类型"><el-select v-model="form.kind"><el-option label="对话模型" value="chat" /><el-option label="Embedding 模型" value="embedding" /></el-select></el-form-item></div><el-form-item label="Base URL"><el-input v-model="form.baseUrl" placeholder="例如：https://example.com/v1" /><small class="form-tip">OpenAI 兼容地址通常包含 /v1。</small></el-form-item><div class="form-grid"><el-form-item label="模型名称"><el-input v-model="form.model" /></el-form-item><el-form-item v-if="form.kind==='embedding'" label="向量维度"><el-input-number v-model="form.dimension" :min="128" :max="4096" /></el-form-item><el-form-item v-else label="思考等级"><el-select v-model="form.reasoningEffort"><el-option label="模型默认" value="default" /><el-option label="关闭（none）" value="none" /><el-option label="最小（minimal）" value="minimal" /><el-option label="低（low）" value="low" /><el-option label="中（medium）" value="medium" /><el-option label="高（high）" value="high" /></el-select><small class="form-tip">仅支持推理等级的模型会生效；不确定时使用“模型默认”。</small></el-form-item></div><el-form-item label="API Key"><el-input v-model="apiKey" type="password" show-password :placeholder="form.id?'留空则不覆盖现有密钥':'请输入 API Key'" /><small class="form-tip">密钥保存后仅展示脱敏值。</small></el-form-item><template v-if="form.kind==='chat'"><el-form-item label="模型内置联网搜索"><el-select v-model="form.webSearchMode"><el-option label="关闭" value="disabled" /><el-option label="Responses API（/responses + web_search，推荐）" value="responses" /><el-option label="Qwen / DashScope（enable_search）" value="qwen" /><el-option label="Chat Completions（web_search_options）" value="openai" /><el-option label="自定义参数" value="custom" /></el-select><small class="form-tip">Responses 模式会调用 /v1/responses，并发送 tools: [{ type: 'web_search' }]。对话测试和机器人回答使用同一配置。</small></el-form-item><el-form-item label="额外请求参数 JSON"><el-input v-model="extraBodyText" type="textarea" :rows="4" placeholder='例如：{"temperature":0.2}' /><small class="form-tip">可留空。思考等级由上方设置统一生成，核心请求字段不会被覆盖。</small></el-form-item></template></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存配置</el-button></template></el-dialog>

    <el-dialog v-model="workbenchVisible" title="模型测试工作台" width="720px" class="model-workbench">
      <template v-if="testingModel"><div class="workbench-model"><span class="entity-icon purple"><el-icon><MagicStick /></el-icon></span><div><strong>{{ testingModel.name }}</strong><span>{{ testingModel.model }} · {{ testingModel.kind === 'chat' ? '对话' : 'Embedding' }}</span></div></div><el-alert :title="`请求 endpoint：${testEndpoint}`" type="info" :closable="false" show-icon class="endpoint-alert" />
      <el-form label-position="top"><el-form-item v-if="testingModel.kind === 'chat'" label="System Prompt（可选）"><el-input v-model="testForm.systemPrompt" type="textarea" :rows="2" placeholder="例如：你是一名简洁、准确的客服助手" /></el-form-item><el-form-item :label="testingModel.kind === 'chat' ? '用户消息' : '测试文本'"><el-input v-model="testForm.input" type="textarea" :rows="4" :placeholder="testingModel.kind === 'chat' ? '输入要发送给模型的消息' : '输入需要生成向量的文本'" /></el-form-item><el-button type="primary" :loading="testing" :disabled="!testForm.input.trim()" @click="runTest">运行测试</el-button></el-form>
      <el-alert v-if="testError" title="测试失败" type="error" :closable="false" show-icon class="test-error"><template #default><pre>{{ testError }}</pre><el-button size="small" :icon="CopyDocument" @click="copyText(testError)">复制错误</el-button></template></el-alert>
      <section v-if="testResult" class="workbench-result"><div class="result-heading"><h3>测试结果 · {{ testResult.model }}</h3><StatusBadge status="success" text="请求成功" /></div><template v-if="testResult.kind === 'chat'"><div class="result-output">{{ testResult.content }}</div><div class="result-stats"><div><span>耗时</span><strong>{{ testResult.latencyMs }}ms</strong></div><div><span>输入 Token</span><strong>{{ testResult.inputTokens }}</strong></div><div><span>输出 Token</span><strong>{{ testResult.outputTokens }}</strong></div></div></template><template v-else><div class="result-stats"><div><span>耗时</span><strong>{{ testResult.latencyMs }}ms</strong></div><div><span>向量维度</span><strong>{{ testResult.dimensions }}</strong></div><div><span>预览项数</span><strong>{{ Math.min(12, testResult.vectorPreview.length) }}</strong></div></div><pre class="vector-preview">[{{ testResult.vectorPreview.slice(0, 12).map(value => Number(value).toFixed(6)).join(', ') }}{{ testResult.vectorPreview.length > 12 ? ', …' : '' }}]</pre></template></section></template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { CopyDocument, MagicStick, Plus } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { api, sanitizeServiceError } from '@/api'
import PageHeader from '@/components/PageHeader.vue'
import StatusBadge from '@/components/StatusBadge.vue'
import type { ModelProfile, ModelTestResult } from '@/types'

const models=ref<ModelProfile[]>([]),activeKind=ref('chat'),dialog=ref(false),apiKey=ref(''),extraBodyText=ref(''),workbenchVisible=ref(false),testing=ref(false),testingModel=ref<ModelProfile>(),testResult=ref<ModelTestResult>(),testError=ref('')
const form=reactive<Partial<ModelProfile>>({});const testForm=reactive({input:'',systemPrompt:''});const filtered=computed(()=>models.value.filter(m=>m.kind===activeKind.value));const testEndpoint=computed(()=>{if(!testingModel.value)return '';const base=testingModel.value.baseUrl.replace(/\/$/,'');if(testingModel.value.kind==='embedding')return `${base}/embeddings`;return `${base}/${testingModel.value.webSearchMode==='responses'?'responses':'chat/completions'}`})
onMounted(load);async function load(){models.value=await api.models.list()};function searchModeText(mode:ModelProfile['webSearchMode']){return ({disabled:'关闭',responses:'Responses Web Search',qwen:'Qwen 内置搜索',openai:'Chat Completions Web Search',custom:'自定义参数'} as Record<string,string>)[mode]||'关闭'};function reasoningText(level:ModelProfile['reasoningEffort']){return ({default:'模型默认',none:'关闭',minimal:'最小',low:'低',medium:'中',high:'高'} as Record<string,string>)[level]||'模型默认'};function openCreate(){Object.assign(form,{id:'',name:'',kind:activeKind.value,provider:'OpenAI Compatible',model:'',baseUrl:'',dimension:1024,status:'online',webSearchMode:'disabled',reasoningEffort:'default',extraBody:{}});apiKey.value='';extraBodyText.value='';dialog.value=true};function edit(m:ModelProfile){Object.assign(form,m);apiKey.value='';extraBodyText.value=Object.keys(m.extraBody||{}).length?JSON.stringify(m.extraBody,null,2):'';dialog.value=true};async function save(){try{form.extraBody=extraBodyText.value.trim()?JSON.parse(extraBodyText.value):{}}catch{ElMessage.error('额外请求参数必须是有效的 JSON 对象');return}if(Array.isArray(form.extraBody)||form.extraBody===null||typeof form.extraBody!=='object'){ElMessage.error('额外请求参数必须是 JSON 对象');return}await api.models.save(form,apiKey.value);await load();dialog.value=false;ElMessage.success('模型配置已保存')}
function openWorkbench(model:ModelProfile){testingModel.value=model;testForm.input=model.kind==='chat'?'请用一句话介绍你自己。':'这是一段用于测试向量模型的文本。';testForm.systemPrompt='';testResult.value=undefined;testError.value='';workbenchVisible.value=true}
async function runTest(){if(!testingModel.value||!testForm.input.trim())return;testing.value=true;testResult.value=undefined;testError.value='';try{const result=await api.models.test(testingModel.value.id,{input:testForm.input.trim(),systemPrompt:testingModel.value.kind==='chat'&&testForm.systemPrompt.trim()?testForm.systemPrompt.trim():undefined});testResult.value=result;testingModel.value.latency=result.latencyMs;testingModel.value.status='online'}catch(error){testingModel.value.status='warning';testError.value=sanitizeServiceError(error instanceof Error?error.message:'模型测试失败')||'模型测试失败'}finally{testing.value=false}}
async function copyText(value:string){await navigator.clipboard?.writeText(value);ElMessage.success('错误信息已复制')}
</script>
